CREATE TABLE accounts (
    id PRIMARY INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    vorname VARCHAR(255) NOT NULL, 
    nachname VARCHAR(255) NOT NULL,
    geburtstag TIMESTAMP NOT NULL,
    wochenstunden INT NOT NULL,
    personalnummer INT NOT NULL,
    email VARCHAR(255) NOT NULL,
    passwortHash VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN NOT NULL, 
    token VARCHAR(255) NOT NULL,
    letzteAktion TIMESTAMP NOT NULL
)
