CREATE TABLE Account (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    email VARCHAR(255) NOT NULL,
    vorname VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    geburtsdatum DATE NOT NULL,
    passwortHash VARCHAR(128), 
    isAdmin BOOLEAN 
);

CREATE TABLE Kurs (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    fach VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    stufe INT, 
    leiter INT,     
    FOREIGN KEY (leiter) REFERENCES Account(id)
);


CREATE TABLE KursTeilnahme (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    account INT NOT NULL,
    kurs INT NOT NULL,
    FOREIGN KEY (account) REFERENCES Account(id),
    FOREIGN KEY (kurs) REFERENCES Kurs(id)
);

CREATE TABLE Unterricht (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    kurs INT NOT NULL,
    beginZeit VARCHAR(5) NOT NULL,
    endZeit VARCHAR(5) NOT NULL,
    FOREIGN KEY (kurs) REFERENCES Kurs(id)
);

CREATE TABLE Stunde (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    unterricht INT NOT NULL,
    beginTimestamp TIMESTAMP NOT NULL,
    endTimestamp TIMESTAMP NOT NULL,
    checkInCode VARCHAR(6) NOT NULL,
    FOREIGN KEY (unterricht) REFERENCES Unterricht(id)
);

CREATE TABLE StundeBewertung (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    account INT NOT NULL,
    stunde INT NOT NULL,
    note INT,
    kommentar VARCHAR(255),
    FOREIGN KEY (account) REFERENCES Account(id),
    FOREIGN KEY (stunde) REFERENCES Stunde(id)
);

CREATE TABLE StundeTeilnahme (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    account INT NOT NULL,
    stunde INT NOT NULL,
    beginTimestamp TIMESTAMP NOT NULL,
    endTimestamp TIMESTAMP,
    note INT,
    FOREIGN KEY (account) REFERENCES Account(id),
    FOREIGN KEY (stunde) REFERENCES Stunde(id)
);

CREATE TABLE Vorstunde(
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1),
    stunde INT NOT NULL,
    vorstunde INT NOT NULL,
    FOREIGN KEY (stunde) REFERENCES Stunde(id),
    FOREIGN KEY (vorstunde) REFERENCES Stunde(id)
);